# Generated by Django 5.1.6 on 2025-02-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance',
            new_name='balance_credits',
        ),
    ]
