# Generated by Django 5.1.6 on 2025-02-15 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=12),
            preserve_default=False,
        ),
    ]
