# Generated by Django 5.1.6 on 2025-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_account_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='current_supply',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='market',
            name='max_supply',
            field=models.FloatField(default=9999.0),
        ),
        migrations.AddField(
            model_name='market',
            name='mining_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='market',
            name='mining_reward',
            field=models.FloatField(default=50.0),
        ),
    ]
