# Generated by Django 5.1.6 on 2025-02-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_transaction_market_price_at_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='last_price',
            new_name='market_price',
        ),
    ]
