# Generated by Django 5.1.6 on 2025-02-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=12),
        ),
    ]
