# Generated by Django 5.1.6 on 2025-02-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_transaction_market_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
