# Generated by Django 5.1.6 on 2025-02-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_market_current_supply_market_max_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='mining_code_uncensored',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
