# Generated by Django 5.1.6 on 2025-02-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_market_mining_code_uncensored'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='market_price_at_trade',
            field=models.FloatField(default=0.0),
        ),
    ]
