# Generated by Django 5.1.6 on 2025-02-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_newsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='mining_code_uncensored',
        ),
    ]
