# Generated by Django 5.1.6 on 2025-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_account_balance_credits_directmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
