# Generated by Django 5.1.6 on 2025-02-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_directmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
    ]
