# Generated by Django 5.1.6 on 2025-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_marketplacelisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
