# Generated by Django 5.1.6 on 2025-02-28 10:07

import bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_alter_marketplacelisting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default=bank.models.default_profile_pic, upload_to='profile_pics/'),
        ),
    ]
