# Generated by Django 5.1.6 on 2025-03-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_directmessage_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='marketplace_videos/'),
        ),
    ]
