# Generated by Django 5.1.6 on 2025-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_remove_directmessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacelisting',
            name='price_cc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
