# Generated by Django 5.1.6 on 2025-03-02 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_marketplacelisting_price_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotMachineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_amount', models.IntegerField()),
                ('currency_used', models.CharField(choices=[('credits', 'Credits'), ('corn_coins', 'Corn Coins')], max_length=10)),
                ('result', models.CharField(max_length=20)),
                ('winnings', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
            ],
        ),
    ]
