# Generated by Django 5.1.6 on 2025-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_slotmachinehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='listing_type',
            field=models.CharField(choices=[('item', 'Item for Sale'), ('job', 'Job Offer'), ('service', 'Service')], max_length=10),
        ),
    ]
