# Generated by Django 5.1.6 on 2025-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplacelisting',
            name='listing_type',
            field=models.CharField(choices=[('item', 'Item'), ('job', 'Job'), ('service', 'Service'), ('food', 'Food')], default='item', max_length=20),
        ),
    ]
